### ISSUE TITLE
support KMS 1.2.357 WZ

### ISSUE THREAD

**Issue by v3921358** [Xterminatorz/WZ-Dumper#3]
Do we support it?

Here are commit from HR:

https://github.com/lastbattle/Harepacker-resurrected/commit/64b74eb5a4bdcdd0fd60022c7ae0a34fc387ae1e

https://github.com/lastbattle/Harepacker-resurrected/commit/df3e587c6fdcc6c58a2fefe609835573dfd3bf37

**Comment by Xterminatorz** [comment]
I made the commit here: https://github.com/Xterminatorz/MapleLib/commit/a1f7326f1aeda1792ccd9ea98d23f32ad139e04e

Unfortunately, I don't have any KMS files to test, so it may or may not work for latest version.
